version: "3"

services:
  app:
    container_name: timesheet
    image: node:20
    volumes:
      - ./:/app
    ports:
      - 3333:3333
    working_dir: /app
    command: npm run dev
    environment:
      DB_HOST: timesheetdb
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: password
      DB_DATABASE: timesheetdb

  database:
    container_name: timesheetdb
    image: postgres:latest
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: timesheetdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust

  pgadmin:
    container_name: timesheetpgadmin
    image: dpage/pgadmin4
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@timesheet.com
      PGADMIN_DEFAULT_PASSWORD: password